highlighter: pygments
markdown: rdiscount
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
gems: [jekyll-paginate]
port: 4000
safe: true
url: http://biomadeira.github.io/vitae
author: Fábio Madeira

# edit this section with your information
# biomadeira.github.io - all contents run on /vitae/
# for a normal use at the base of the server change it to "/"
baseurl: /vitae/
title: Matthew Klein Resume
name: Matthew Klein
email: gmattklein@gmail.com
email_full: mailto:gmattklein@gmail.com
website: matthewkle.in
website_full: https://matthewkle.in
github: github.com/kleinma
facebook: facebook.com/kleinma
tel: +1 330 447 6876
tel_full: tel:+13304476876
google_maps: 'https://www.google.co.uk/maps/place/44+Perth+St,+Edinburgh,+Edinburgh+City+EH3+5BL'
address: 2169 Oakdale Rd
postcode: 44118
city: Cleveland Heigths
state: OH
country: United States
google_analytics: UA-69300817-1

# needed for travis-ci build
exclude: [vendor]
